---
abstract: 'Just use popular RDF namespace prefixes from prefix.cc'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-NS
requires:
  File::ShareDir: 1.00
resources:
  bugtracker: https://github.com/nichtich/RDF-NS/issues
  homepage: https://github.com/nichtich/RDF-NS
  repository: https://github.com/nichtich/RDF-NS.git
version: 20131115
