---
abstract: 'Just use popular RDF namespace prefixes from prefix.cc'
author:
  - 'Jakob Voss'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-NS
requires:
  File::ShareDir: 1.00
resources:
  bugtracker: https://github.com/gbv/RDF-NS/issues
  repository: https://github.com/gbv/RDF-NS
version: 20111102
